import { families, hotels, itinerary, locations, members } from './data/trip.js';
import { calculateBalances, familyTotals, simplifyDebt, whatsappSettlementSummary } from './lib/expenseEngine.js';

const KEY = 'bharatbhraman-state-v1';
const money = (n) => `₹${Math.round(n).toLocaleString('en-IN')}`;
const nameOf = (id) => members.find((m) => m.id === id)?.name || id;
const defaults = {
  expenses: [
    { id: 'sample-1', title: 'Dehradun welcome snacks', amount: 1600, paidBy: [{ memberId: 'sanket', amount: 1600 }], date: '2026-06-20', category: 'Food', location: 'Dehradun', notes: 'Sample expense; edit after real entry.', participants: [], splitType: 'equal', linkedDayId: 'day-2' },
    { id: 'sample-2', title: 'Gocars fuel advance', amount: 5000, paidBy: [{ memberId: 'milind', amount: 5000 }], date: '2026-06-21', category: 'Fuel', location: 'Dehradun', notes: 'Sample vehicle cost.', participants: members.map((m) => ({ memberId: m.id })), splitType: 'vehicle', linkedDayId: 'day-3' }
  ],
  transfers: [{ id: 'transfer-1', from: 'sanket', to: 'milind', amount: 1000, date: '2026-06-21', note: 'Sample advance transfer', status: 'completed' }],
  files: [], notes: [], syncQueue: []
};
let state = JSON.parse(localStorage.getItem(KEY) || 'null') || defaults;
let page = 'home';
const save = () => localStorage.setItem(KEY, JSON.stringify(state));
const card = (title, body, meta = '') => `<section class="glass card"><div class="section-title"><h2>${title}</h2><span>${meta}</span></div>${body}</section>`;
const render = () => {
  const balances = calculateBalances(state.expenses, state.transfers), settlements = simplifyDebt(balances), total = state.expenses.reduce((s,e)=>s+e.amount*(e.isRefund?-1:1),0), famTotals = familyTotals(balances);
  document.querySelector('#root').innerHTML = `<div class="app-shell"><header class="topbar"><button id="planBtn">☰</button><div><strong>BharatBhraman</strong><span>Premium offline family trip OS</span></div><button data-page="documents">⇧</button></header><div id="planner" hidden>${planning()}</div><div class="content-grid"><div>${pages[page](balances, settlements, total, famTotals)}</div>${assistant(balances, settlements)}</div>${nav()}</div>`;
  bind();
};
const nav = () => `<nav class="bottom-nav">${[['home','⌂','Home'],['itinerary','🗓','Itinerary'],['expenses','₹','Expenses'],['map','⌖','Map'],['memories','◎','Memories'],['documents','▣','Docs']].map(([id, icon, label]) => `<button data-page="${id}" class="${page===id?'active':''}"><b>${icon}</b><span>${label}</span></button>`).join('')}</nav>`;
const stat = (icon,label,value,hint) => `<article class="stat-card"><div class="icon-bubble">${icon}</div><div><p>${label}</p><strong>${value}</strong><span>${hint}</span></div></article>`;
const pages = {
  home: (balances, settlements, total, famTotals) => `<main class="page-stack"><section class="hero glass"><div class="hero-copy"><span class="eyebrow">Uttarakhand Family Travel OS</span><h1>BharatBhraman</h1><p>Mumbai → Delhi → Dehradun → Chakrata → Hanol → Mussoorie → Haridwar → Mumbai</p><div class="hero-actions"><button data-page="documents">Upload bill</button><button data-page="expenses" class="ghost">Add expense</button></div></div><div class="route-orb"><strong>9 days</strong><span>8 members · 3 families</span></div></section><section class="stats-grid">${stat('👨‍👩‍👧‍👦','Members','8','Sanket, Milind and Sharad families')}${stat('₹','Actual expense',money(total),'Budget to be confirmed.')}${stat('✅','Pending settlements',settlements.length,`${money(settlements.reduce((s,x)=>s+x.amount,0))} open`)}${stat('☁','Offline ready','Local-first','PWA cache + browser storage')}</section><section class="two-col">${card('Trip progress','<div class="progress"><span style="width:0%"></span></div><p class="muted">Trip starts on 19 Jun 2026. Upcoming stay: Train.</p>','0%')}${card('Weather','<p>Open‑Meteo is the planned free weather source. No API key required. Exact city forecast can be enabled once date/location pins are confirmed.</p>','Open‑Meteo')}</section>${card('Family spend analytics',`<div class="bar-chart">${famTotals.map((f)=>`<div><span>${f.name}</span><i style="width:${Math.max(6,Math.abs(f.owed)/(total||1)*100)}%"></i><b>${money(f.owed)}</b></div>`).join('')}</div>`,'Recharts-ready')}${card('Hotel tracker',`<div class="mini-list">${hotels.map((h)=>`<div><b>${h.name}</b><span>Booking ${h.bookingAmount} · Advance ${h.advancePaid}</span><small>Pending amount: ${h.pendingAmount}</small></div>`).join('')}</div>`,'Stays')}</main>`,
  itinerary: () => `<main class="page-stack">${itinerary.map((d)=>`<article class="glass day-card"><div class="day-head"><div><span>${d.label}</span><h2>${d.route}</h2><p>${d.mode}</p></div><button>✓ Mark</button></div><div class="tag-row"><span>${d.stay}</span><span>${d.seniorSuitability}</span></div><ul>${d.keyDetails.map((x)=>`<li>${x}</li>`).join('')}</ul><div class="detail-grid"><div><b>Food</b>${d.food.map((x)=>`<p>${x}</p>`).join('')}</div><div><b>Photos</b>${d.photoSpots.map((x)=>`<p>${x}</p>`).join('')}</div></div><div class="action-row"><button>Add note</button><button data-page="expenses">Add expense</button><button data-page="documents">Upload file</button><button data-page="map">Add pin</button></div></article>`).join('')}</main>`,
  expenses: (balances, settlements) => `<main class="page-stack">${card('Add expense',`<form id="expenseForm" class="form-grid"><input name="title" placeholder="Title" required><input name="amount" placeholder="Amount" inputmode="decimal" required><select name="paidBy">${members.map((m)=>`<option value="${m.id}">${m.name}</option>`)}</select><select name="splitType">${['equal','selected','family','couple','room','bed','vehicle','weighted','exact','percentage'].map((s)=>`<option>${s}</option>`)}</select><button>Add expense</button></form>`,'Splitwise-style')}${card('Member transfer',`<form id="transferForm" class="form-grid"><select name="from">${members.map((m)=>`<option value="${m.id}">${m.name}</option>`)}</select><select name="to">${members.map((m)=>`<option value="${m.id}">${m.name}</option>`)}</select><input name="amount" placeholder="Amount" inputmode="decimal" required><button>Record transfer</button></form>`,'Separate ledger')}${card('Balances',`<div class="table-list">${balances.map((b)=>`<div><b>${nameOf(b.memberId)}</b><span>Paid ${money(b.paid)} · Owed ${money(b.owed)} · Transfers in ${money(b.transfersIn)}</span><strong class="${b.net>=0?'positive':'negative'}">${money(b.net)}</strong></div>`).join('')}</div>`,'Paid vs owed')}${card('Minimum settlements',`<div class="action-row"><button id="whatsapp">WhatsApp summary</button><button id="excel">Excel CSV</button><button id="pdf">PDF print</button></div><div class="table-list">${settlements.map((s)=>`<div><b>${nameOf(s.from)} → ${nameOf(s.to)}</b><span>${s.reason}</span><strong>${money(s.amount)}</strong></div>`).join('')}</div>`,'Simplify debt')}</main>`,
  map: () => `<main class="page-stack">${card('OpenStreetMap route board',`<div class="map-shell"><div class="map-route">${locations.map((p,i)=>`<div class="map-pin-row"><span>${i+1}</span><b>${p.name}</b><small>Coordinates to be confirmed.</small></div>`).join('')}</div></div><p class="muted">Exact coordinates are intentionally not invented. Add confirmed coordinates later to render Leaflet/OpenStreetMap hotel, sightseeing, food, fuel and memory pins.</p>`,'Leaflet-ready')}</main>`,
  memories: () => `<main class="page-stack">${card('Memories gallery',`<div class="story-row">${itinerary.map((d)=>`<div class="story"><span>${d.label}</span><b>${d.route.split('→').at(-1).trim()}</b></div>`).join('')}</div><div class="gallery-grid">${state.files.filter(f=>f.type.startsWith('image/')||f.type.startsWith('video/')).map((f)=>f.type.startsWith('image/')?`<a href="${f.dataUrl}" download="${f.name}"><img src="${f.dataUrl}" alt="${f.name}"></a>`:`<a class="video-tile" href="${f.dataUrl}" download="${f.name}">Video<br>${f.name}</a>`).join('') || '<p class="muted">No photos/videos yet. Upload originals in Documents.</p>'}</div>`,'Story mode')}</main>`,
  documents: () => `<main class="page-stack"><section class="glass card upload-card"><h2>Upload bills, tickets, IDs, photos and videos</h2><p>Prototype preserves originals locally as browser data URLs. Supabase Storage can be connected later for cloud sync.</p><label class="upload-button"><input id="fileInput" type="file" multiple>Choose files</label></section>${card('Document vault',`<div class="doc-list">${state.files.map((f)=>`<a href="${f.dataUrl}" download="${f.name}"><span>▣</span><div><b>${f.name}</b><span>${f.type} · ${(f.size/1024).toFixed(1)} KB · tags to be confirmed.</span></div></a>`).join('')}</div>`,`${state.files.length} files`)}</main>`
};
const planning = () => `<main class="page-stack">${card('Product & architecture blueprint',`<div class="blueprint"><p><b>Vision:</b> private family travel OS for 8 people: Splitwise + Maps + Airbnb stay tracker + Instagram diary.</p><p><b>Architecture:</b> static React/PWA-ready frontend, free hosting, localStorage now, IndexedDB/Supabase later.</p><p><b>UX flow:</b> large mobile cards, bottom navigation, senior-readable dark glassmorphism.</p><p><b>Components:</b> Dashboard, ItineraryCards, ExpenseLedger, TransferForm, SettlementTable, UploadVault, RouteMap, MemoryGallery, Assistant.</p><p><b>Schema:</b> users, families, members, days, locations, hotels, vehicles, expenses, participants, transfers, settlements, files, notes, sync queue.</p><p><b>Logic:</b> equal, selected, family, room/bed, exact, percentage, weighted, multiple payers, refunds, transfers, net balance and simplified debt are implemented in src/lib/expenseEngine.js.</p><p><b>Free APIs:</b> OpenStreetMap/Leaflet, OSRM/OpenRouteService free tier, Open‑Meteo, optional Supabase free tier.</p><p><b>Exports:</b> CSV download now; SheetJS/jsPDF upgrade path documented for full Excel/PDF.</p><p><b>Deployment:</b> npm run build, publish dist/ to GitHub Pages, Netlify, Vercel or Replit.</p></div>`,'16-point plan')}</main>`;
const assistant = (balances, settlements) => { const high = [...balances].sort((a,b)=>b.paid-a.paid)[0]; return `<aside class="assistant glass"><div><b>🤖 Family Assistant</b></div><p><b>Today’s plan:</b> Current date is before the trip; first plan is Mumbai → Delhi on 19 Jun 2026.</p><p><b>Who paid most?</b> ${high ? nameOf(high.memberId) : 'To be confirmed.'}</p><p><b>Pending settlements:</b> ${settlements.length} transactions, ${money(settlements.reduce((s,x)=>s+x.amount,0))} total.</p><p><b>Missing documents:</b> Train names, Haridwar hotel, hotel prices and booking amounts are to be confirmed.</p><p><b>Travel diary:</b> “Eight of us began a hill journey from Mumbai toward quiet temples, waterfalls and valleys of Uttarakhand.”</p><small>${state.syncQueue.length} offline sync items queued.</small></aside>`; };
function bind() {
  document.querySelectorAll('[data-page]').forEach((b)=>b.addEventListener('click',()=>{page=b.dataset.page; render();}));
  document.querySelector('#planBtn')?.addEventListener('click',()=>{const p=document.querySelector('#planner'); p.hidden=!p.hidden;});
  document.querySelector('#expenseForm')?.addEventListener('submit',(e)=>{e.preventDefault(); const f=new FormData(e.target); const amount=Number(f.get('amount')); if(!amount) return; const ex={ id:`expense-${Date.now()}`, title:f.get('title'), amount, paidBy:[{memberId:f.get('paidBy'),amount}], date:new Date().toISOString().slice(0,10), category:'Other', location:'To be confirmed.', notes:'', participants:members.map((m)=>({memberId:m.id})), splitType:f.get('splitType')}; state.expenses=[ex,...state.expenses]; state.syncQueue.push({id:`sync-${Date.now()}`,entity:'expense',operation:'create',payload:ex,createdAt:new Date().toISOString()}); save(); render();});
  document.querySelector('#transferForm')?.addEventListener('submit',(e)=>{e.preventDefault(); const f=new FormData(e.target); const amount=Number(f.get('amount')); if(!amount||f.get('from')===f.get('to')) return; const t={id:`transfer-${Date.now()}`,from:f.get('from'),to:f.get('to'),amount,date:new Date().toISOString().slice(0,10),note:'Member transfer',status:'completed'}; state.transfers=[t,...state.transfers]; state.syncQueue.push({id:`sync-${Date.now()}`,entity:'transfer',operation:'create',payload:t,createdAt:new Date().toISOString()}); save(); render();});
  document.querySelector('#fileInput')?.addEventListener('change', async (e)=>{ const files = await Promise.all([...e.target.files].map((file)=>new Promise((resolve)=>{ const reader=new FileReader(); reader.onload=()=>resolve({id:`file-${Date.now()}-${Math.random()}`,name:file.name,type:file.type||'application/octet-stream',size:file.size,tags:['To be confirmed.'],createdAt:new Date().toISOString(),dataUrl:reader.result}); reader.readAsDataURL(file);}))); state.files=[...files,...state.files]; save(); render(); });
  document.querySelector('#whatsapp')?.addEventListener('click',()=>navigator.clipboard?.writeText(whatsappSettlementSummary(simplifyDebt(calculateBalances(state.expenses,state.transfers)))));
  document.querySelector('#excel')?.addEventListener('click',()=>{ const rows=simplifyDebt(calculateBalances(state.expenses,state.transfers)).map((s)=>`${nameOf(s.from)},${nameOf(s.to)},${s.amount},${s.status}`).join('\n'); const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([`From,To,Amount,Status\n${rows}`],{type:'text/csv'})); a.download='BharatBhraman-settlement.csv'; a.click(); });
  document.querySelector('#pdf')?.addEventListener('click',()=>print());
}
if ('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js');
render();
